import sys
import re

MaxCode = 0x0010FFFF

dic = {
    'Aghb': 'Caucasian_Albanian',
    'Ahom': 'Ahom',
    'Arab': 'Arabic',
    'Armi': 'Imperial_Aramaic',
    'Armn': 'Armenian',
    'Avst': 'Avestan',
    'Bali': 'Balinese',
    'Bamu': 'Bamum',
    'Bass': 'Bassa_Vah',
    'Batk': 'Batak',
    'Beng': 'Bengali',
    'Bopo': 'Bopomofo',
    'Brah': 'Brahmi',
    'Brai': 'Braille',
    'Bugi': 'Buginese',
    'Buhd': 'Buhid',
    'Cakm': 'Chakma',
    'Cans': 'Canadian_Aboriginal',
    'Cari': 'Carian',
    'Cham': 'Cham',
    'Cher': 'Cherokee',
    'Copt': 'Coptic',
    'Cprt': 'Cypriot',
    'Cyrl': 'Cyrillic',
    'Deva': 'Devanagari',
    'Dsrt': 'Deseret',
    'Dupl': 'Duployan',
    'Egyp': 'Egyptian_Hieroglyphs',
    'Elba': 'Elbasan',
    'Ethi': 'Ethiopic',
    'Geor': 'Georgian',
    'Glag': 'Glagolitic',
    'Goth': 'Gothic',
    'Gran': 'Grantha',
    'Grek': 'Greek',
    'Gujr': 'Gujarati',
    'Guru': 'Gurmukhi',
    'Hang': 'Hangul',
    'Hani': 'Han',
    'Hano': 'Hanunoo',
    'Hatr': 'Hatran',
    'Hebr': 'Hebrew',
    'Hira': 'Hiragana',
    'Hluw': 'Anatolian_Hieroglyphs',
    'Hmng': 'Pahawh_Hmong',
    'Hrkt': 'Katakana_Or_Hiragana',
    'Hung': 'Old_Hungarian',
    'Ital': 'Old_Italic',
    'Java': 'Javanese',
    'Kali': 'Kayah_Li',
    'Kana': 'Katakana',
    'Khar': 'Kharoshthi',
    'Khmr': 'Khmer',
    'Khoj': 'Khojki',
    'Knda': 'Kannada',
    'Kthi': 'Kaithi',
    'Lana': 'Tai_Tham',
    'Laoo': 'Lao',
    'Latn': 'Latin',
    'Lepc': 'Lepcha',
    'Limb': 'Limbu',
    'Lina': 'Linear_A',
    'Linb': 'Linear_B',
    'Lisu': 'Lisu',
    'Lyci': 'Lycian',
    'Lydi': 'Lydian',
    'Mahj': 'Mahajani',
    'Mand': 'Mandaic',
    'Mani': 'Manichaean',
    'Mend': 'Mende_Kikakui',
    'Merc': 'Meroitic_Cursive',
    'Mero': 'Meroitic_Hieroglyphs',
    'Mlym': 'Malayalam',
    'Modi': 'Modi',
    'Mong': 'Mongolian',
    'Mroo': 'Mro',
    'Mtei': 'Meetei_Mayek',
    'Mult': 'Multani',
    'Mymr': 'Myanmar',
    'Narb': 'Old_North_Arabian',
    'Nbat': 'Nabataean',
    'Nkoo': 'Nko',
    'Ogam': 'Ogham',
    'Olck': 'Ol_Chiki',
    'Orkh': 'Old_Turkic',
    'Orya': 'Oriya',
    'Osma': 'Osmanya',
    'Palm': 'Palmyrene',
    'Pauc': 'Pau_Cin_Hau',
    'Perm': 'Old_Permic',
    'Phag': 'Phags_Pa',
    'Phli': 'Inscriptional_Pahlavi',
    'Phlp': 'Psalter_Pahlavi',
    'Phnx': 'Phoenician',
    'Plrd': 'Miao',
    'Prti': 'Inscriptional_Parthian',
    'Rjng': 'Rejang',
    'Runr': 'Runic',
    'Samr': 'Samaritan',
    'Sarb': 'Old_South_Arabian',
    'Saur': 'Saurashtra',
    'Sgnw': 'SignWriting',
    'Shaw': 'Shavian',
    'Shrd': 'Sharada',
    'Sidd': 'Siddham',
    'Sind': 'Khudawadi',
    'Sinh': 'Sinhala',
    'Sora': 'Sora_Sompeng',
    'Sund': 'Sundanese',
    'Sylo': 'Syloti_Nagri',
    'Syrc': 'Syriac',
    'Tagb': 'Tagbanwa',
    'Takr': 'Takri',
    'Tale': 'Tai_Le',
    'Talu': 'New_Tai_Lue',
    'Taml': 'Tamil',
    'Tavt': 'Tai_Viet',
    'Telu': 'Telugu',
    'Tfng': 'Tifinagh',
    'Tglg': 'Tagalog',
    'Thaa': 'Thaana',
    'Thai': 'Thai',
    'Tibt': 'Tibetan',
    'Tirh': 'Tirhuta',
    'Ugar': 'Ugaritic',
    'Vaii': 'Vai',
    'Wara': 'Warang_Citi',
    'Xpeo': 'Old_Persian',
    'Xsux': 'Cuneiform',
    'Yiii': 'Yi',
    'Zinh': 'Inherited',
    'Zyyy': 'Common',
    'Zzzz': 'Unknown',
}

values = [-1] * (MaxCode + 1)
rHeader = re.compile(r"# Script_Extensions=(.*)")

id = 0
for line in sys.stdin.readlines():
    m = rHeader.match(line)
    if m:
        print('{')
        for sc in [dic[x] for x in m.group(1).split(' ')]:
            print('    Script::%s, ' % sc)
        print('},')
        id += 1
